<?php

declare(strict_types=1);

namespace Shipard\Core\Server;

/**
 * Jediný zdroj pravdy pro systémový cron: sloty, cesty k lock/heartbeat
 * souborům a šablona /etc/cron.d/shipard. Sdílí ji dispatcher
 * (`shpd-server cron`), generátor (`cron-install`) a doctor.
 */
final class CronProvisioner
{
    public const TEMPLATE_VERSION = 1;
    public const CRON_FILE = '/etc/cron.d/shipard';
    public const RUN_DIR = '/opt/shipard/run';
    public const CRON_LOG = '/opt/shipard/log/cron.log';

    public const SLOTS = ['minute', 'five-minutes', 'daily', 'weekly'];

    /** slot → cron časový předpis; daily/weekly mimo celé hodiny */
    private const SCHEDULE = [
        'minute'       => '* * * * *',
        'five-minutes' => '*/5 * * * *',
        'daily'        => '17 3 * * *',
        'weekly'       => '43 4 * * 0',
    ];

    /** Kompletní obsah /etc/cron.d/shipard. Žádné per-DS řádky — DS iteruje dispatcher. */
    public function renderTemplate(string $phpBinary, string $repoRoot, string $user, string $cronLogPath = self::CRON_LOG): string
    {
        $lines = [
            sprintf(
                '# Shipard cron — generated by `shpd-server cron-install`, template version %d. DO NOT EDIT.',
                self::TEMPLATE_VERSION,
            ),
            '# Regenerated by `shpd-server upgrade` when the template or paths change.',
            'SHELL=/bin/sh',
            'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
            '',
        ];

        $maxScheduleLen = max(array_map('strlen', self::SCHEDULE));
        foreach (self::SLOTS as $slot) {
            $lines[] = sprintf(
                '%s %s %s %s/bin/shpd-server cron --slot=%s >> %s 2>&1',
                str_pad(self::SCHEDULE[$slot], $maxScheduleLen),
                $user,
                $phpBinary,
                $repoRoot,
                $slot,
                $cronLogPath,
            );
        }

        return implode("\n", $lines) . "\n";
    }

    /** Verze z marker hlavičky; null když marker chybí (ručně přepsaný soubor). */
    public static function parseTemplateVersion(string $content): ?int
    {
        if (preg_match('/template version (\d+)/', $content, $m) !== 1) {
            return null;
        }
        return (int) $m[1];
    }

    public static function heartbeatPath(string $slot, string $runDir = self::RUN_DIR): string
    {
        return $runDir . '/cron-' . $slot . '.heartbeat';
    }

    public static function lockPath(string $slot, string $runDir = self::RUN_DIR): string
    {
        return $runDir . '/cron-' . $slot . '.lock';
    }
}
