# Produkce — subdoména + SSL
# Použití: https://demo.shipard.cz/api/v1/...
server {
    listen 443 ssl;
    server_name *.shipard.cz;

    root /opt/shipard/shpd/public;
    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param REQUEST_URI $request_uri;
        include fastcgi_params;
    }
}
