<?php

declare(strict_types=1);

namespace Shipard\Tests\Unit\Module\Core\Mail;

use PHPUnit\Framework\TestCase;
use Shipard\Module\Core\Mail\BulkHeadersDetector;

/**
 * Deterministická detekce bulk hlaviček z raw .eml — jen hlavičkový blok,
 * folding, CRLF/LF tolerance.
 */
class BulkHeadersDetectorTest extends TestCase
{
    private BulkHeadersDetector $detector;

    protected function setUp(): void
    {
        $this->detector = new BulkHeadersDetector();
    }

    private function eml(array $headerLines, string $body = "Hello.\n"): string
    {
        $base = [
            'From: sender@example.com',
            'To: user@firma.cz',
            'Subject: Test',
        ];
        return implode("\r\n", array_merge($base, $headerLines)) . "\r\n\r\n" . $body;
    }

    public function testPlainMessageIsNotBulk(): void
    {
        $this->assertFalse($this->detector->detect($this->eml([])));
    }

    public function testListUnsubscribePresenceIsBulk(): void
    {
        $raw = $this->eml(['List-Unsubscribe: <https://example.com/unsub>']);
        $this->assertTrue($this->detector->detect($raw));
    }

    public function testListIdPresenceIsBulk(): void
    {
        $raw = $this->eml(['List-Id: Newsletter <news.example.com>']);
        $this->assertTrue($this->detector->detect($raw));
    }

    public function testPrecedenceBulkIsBulk(): void
    {
        $this->assertTrue($this->detector->detect($this->eml(['Precedence: bulk'])));
    }

    public function testPrecedenceListIsBulk(): void
    {
        $this->assertTrue($this->detector->detect($this->eml(['Precedence: list'])));
    }

    public function testPrecedenceFirstClassIsNotBulk(): void
    {
        $this->assertFalse($this->detector->detect($this->eml(['Precedence: first-class'])));
    }

    public function testAutoSubmittedAutoGeneratedIsBulk(): void
    {
        $this->assertTrue($this->detector->detect($this->eml(['Auto-Submitted: auto-generated'])));
    }

    public function testAutoSubmittedNoIsNotBulk(): void
    {
        $this->assertFalse($this->detector->detect($this->eml(['Auto-Submitted: no'])));
    }

    public function testHeaderNamesAreCaseInsensitive(): void
    {
        $raw = $this->eml(['LIST-UNSUBSCRIBE: <mailto:unsub@example.com>']);
        $this->assertTrue($this->detector->detect($raw));

        $raw = $this->eml(['precedence: BULK']);
        $this->assertTrue($this->detector->detect($raw));
    }

    public function testFoldedHeaderIsDetected(): void
    {
        $raw = $this->eml([
            "List-Unsubscribe: <https://example.com/unsub?id=123>,\r\n <mailto:unsub@example.com>",
        ]);
        $this->assertTrue($this->detector->detect($raw));
    }

    public function testLfOnlyLineEndingsWork(): void
    {
        $raw = "From: a@b.cz\nSubject: T\nPrecedence: bulk\n\nBody\n";
        $this->assertTrue($this->detector->detect($raw));
    }

    public function testListUnsubscribeInBodyDoesNotMatch(): void
    {
        $raw = $this->eml([], "Forwarded headers below:\r\nList-Unsubscribe: <https://example.com/x>\r\n");
        $this->assertFalse($this->detector->detect($raw));
    }

    public function testPrecedenceInBodyDoesNotMatch(): void
    {
        $raw = $this->eml([], "Precedence: bulk\r\n");
        $this->assertFalse($this->detector->detect($raw));
    }

    public function testMessageWithoutBodySeparatorStillParses(): void
    {
        $raw = "From: a@b.cz\r\nList-Id: <l.example.com>";
        $this->assertTrue($this->detector->detect($raw));
    }
}
