<?php

declare(strict_types=1);

namespace Shipard\Command\DataSource;

use Shipard\Core\Config\DataSourceConfig;
use Shipard\Core\Database\DataSourceConnection;
use Shipard\Module\Core\Mail\FakeIncomingMessageGenerator;
use Shipard\Module\Core\Mail\FakeMailboxGenerator;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Remove all core.mail test data generated by `seed-mail`.
 *
 * Maže postupně: analýzy → attachments → zprávy → schránky, vše s prefixem TEST-.
 * Soubory attachmentů na disku nechává být — v testovacích DS jsou orphan soubory
 * akceptovatelné, při potřebě čisté DS stačí znovu spustit `ds-create`.
 */
class SeedMailClearCommand extends Command
{
    private const MAIL_TABLE_ID = 303;

    public function __construct(
        private readonly ?DataSourceConfig $dsConfig = null,
        private readonly ?DataSourceConnection $dsConnection = null,
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName('seed-mail-clear')
             ->setDescription('Remove all core.mail seed data (TEST- mailboxes + TEST-MSG- messages + related)');
    }

    protected function getDataSourceDir(): string
    {
        return getcwd();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $dsDir = $this->getDataSourceDir();

        if ($this->dsConfig === null && !file_exists($dsDir . '/config/main.json')) {
            $output->writeln('<e>Error: Not a Shipard data source directory</e>');
            return Command::FAILURE;
        }

        $dsConfig = $this->dsConfig ?? new DataSourceConfig($dsDir);
        $dsConnection = $this->dsConnection ?? new DataSourceConnection($dsConfig);

        $seedMessages = $dsConnection->fetchAll(
            'SELECT id FROM core_mail_incoming_messages WHERE message_id LIKE %s',
            FakeIncomingMessageGenerator::ID_PREFIX . '%',
        );
        $messageIds = array_map(static fn(array $row): int => (int) $row['id'], $seedMessages);

        $seedMailboxes = $dsConnection->fetchAll(
            'SELECT id FROM core_mail_mailboxes WHERE mailbox_id LIKE %s',
            FakeMailboxGenerator::PREFIX . '%',
        );
        $mailboxIds = array_map(static fn(array $row): int => (int) $row['id'], $seedMailboxes);

        if ($messageIds === [] && $mailboxIds === []) {
            $output->writeln('No seeded mail data found.');
            return Command::SUCCESS;
        }

        $output->writeln('<info>Clearing core.mail seed data...</info>');
        $output->writeln('  Found ' . count($messageIds) . ' TEST-MSG- messages');
        $output->writeln('  Found ' . count($mailboxIds) . ' TEST- mailboxes');

        $dsConnection->execute('START TRANSACTION');

        try {
            $analysesDeleted = 0;
            $attachmentsDeleted = 0;

            if ($messageIds !== []) {
                $msgList = implode(',', $messageIds);

                $dsConnection->execute('DELETE FROM core_mail_message_analyses WHERE message IN (' . $msgList . ')');
                $analysesDeleted = $this->getAffectedRows($dsConnection);

                $dsConnection->execute(
                    'DELETE FROM core_attachments_files WHERE table_id = %i AND record_id IN (' . $msgList . ')',
                    self::MAIL_TABLE_ID,
                );
                $attachmentsDeleted = $this->getAffectedRows($dsConnection);

                $dsConnection->execute('DELETE FROM core_mail_incoming_messages WHERE id IN (' . $msgList . ')');
                $output->writeln('  Deleted analyses:    ' . $analysesDeleted);
                $output->writeln('  Deleted attachments: ' . $attachmentsDeleted);
                $output->writeln('  Deleted messages:    ' . count($messageIds));
            }

            if ($mailboxIds !== []) {
                $mbxList = implode(',', $mailboxIds);
                // Bezpečnostní kontrola — nesmažeme schránku, která po mazání zpráv
                // ještě má nějakou zprávu (mohlo by jít o produkční zprávu ručně přiřazenou
                // k testovací schránce)
                $stillUsed = $dsConnection->fetchRow(
                    'SELECT COUNT(*) AS cnt FROM core_mail_incoming_messages WHERE mailbox IN (' . $mbxList . ')',
                );
                if ($stillUsed !== null && (int) $stillUsed['cnt'] > 0) {
                    $output->writeln('<comment>Warning: ' . $stillUsed['cnt'] . ' non-seed messages still reference TEST- mailboxes — skipping mailbox delete.</comment>');
                } else {
                    $dsConnection->execute('DELETE FROM core_mail_mailboxes WHERE id IN (' . $mbxList . ')');
                    $output->writeln('  Deleted mailboxes:   ' . count($mailboxIds));
                }
            }

            $dsConnection->execute('COMMIT');
        } catch (\Throwable $e) {
            $dsConnection->execute('ROLLBACK');
            $output->writeln('<e>Error: ' . $e->getMessage() . '</e>');
            $output->writeln('<e>Transaction rolled back — no data was deleted.</e>');
            return Command::FAILURE;
        }

        $output->writeln('');
        $output->writeln('<info>Seed data cleared.</info>');
        return Command::SUCCESS;
    }

    private function getAffectedRows(DataSourceConnection $dsConnection): int
    {
        try {
            $row = $dsConnection->fetchRow('SELECT ROW_COUNT() AS cnt');
            return $row !== null ? (int) $row['cnt'] : 0;
        } catch (\Throwable) {
            return 0;
        }
    }
}
